### ISSUE TITLE
Saving SPM.mat -v7.3 issue with nipype-0.12.1-py27_0

### ISSUE THREAD

**Issue by gladomat** [psiden/BFAST3D#1]
I've come across an error when running BFAST3D and nipype 0.12.1. When it tries to load a saved SPM.mat file it can't because it has trouble with -v7.3 mat files. I've changed it in my code to 
`save('SPM.mat', 'SPM', spm_get_defaults('mat.format'));`

This is a nipype Problem, as python has trouble loading these mat files.

**Comment by psiden** [comment]
Ok, good to know. The -v7.3 switch is needed once the save-file reaches a certain size, or you get an error in Matlab. I guess your solution is good as long as save files are not too big, but I don't want to make a permanent change.
