### ISSUE TITLE
The function 'spm_spm_vb' corresponding to the input parameter of type 'struct' is not defined.

### ISSUE THREAD

**Issue by caixixixi** [psiden/BFAST3D#2]
Sorry to interrupt,i am just learning fmri.When i ran the code, an error appeare.I have put spm12 and ds105 in the BFAST3D-master folder,deleted the spm_spm_vb.m-file in the new spm12-directory , copied the svb-folder from this package into the new spm12-directory and changed the variable SPM.ParallelGMRFSampling to 0.
Firstly,i ran runExample.m step by step.when i ran 'preprocessing(dataPath,SPMPath,subject)',failed.so i change 'dataPath = '.../ds105/';outputPath = '.../Results/';SPMPath = '.../spm12/';'It is correct?
But when i  continue to 'runSVB(dataPath,outputPath,SPMPath,subject,VBMethod);',matlab show 'The function 'spm_spm_vb' corresponding to the input parameter of type 'struct' is not defined.'In file "D:\bishe\BFAST3D-master\spm12\config\spm_run_fmri_est.m" (v5809), function "spm_run_fmri_est" at line 282.The following modules did not run:Failed: Model estimation.
what should i do next?please help me.

**Comment by psiden** [comment]
Hi,

I do not recognize this problem. Are you able to run the normal SPM first-level Bayesian analysis without errors?

Best,
Per

**Comment by caixixixi** [comment]
sorry,i don't know how to run the normal SPM first-level Bayesian analysis.
matlab show :
'Running 'Model estimation'
Zero padding.Zero padding.Zero padding.Zero padding.Zero padding.Failed  'Model estimation'
In file "D:\BFAST3D-master\spm12\config\spm_run_fmri_est.m" (v5809), function "spm_run_fmri_est" at line 282.
The following modules did not run:
Failed: Model estimation'

**Comment by psiden** [comment]
You can try to go through the tutorial in Chapter 31 (especially the Bayesian part in Chapter 31.4) in the SPM12 manual available here: http://www.fil.ion.ucl.ac.uk/spm/doc/. See if you can run that without errors
